### ISSUE TITLE
Autofocus on MBDialog causes an error when the focussed element is a MBNumericDoubleField

### ISSUE THREAD

**Issue by martindekock** [Material-Blazor/Material.Blazor#481] opened 2021-04-21 14:29 UTC
When the first lement inside the MBDialog body is a MBNumericDoubleField, the auto-focus seems to cause an exception in the JS.
When I put any other focusable element before the MBNumericDoubleField, it does not throw the exception.
![Capture2](https://user-images.githubusercontent.com/34054219/115570843-bd660d80-a2be-11eb-9d6b-e1ffed8d3623.PNG)

**Comment by stefanloerwald** [comment] 2021-04-21 14:54
Hi @martindekock,

I just tried to reproduce this issue, but I get a different error. Could you please say which version you are using?

The code I used was
```
@code {
    MBDialog dialog;
    double value { get; set; }
} 
<MBButton Label="Open Dialog" @onclick="() => dialog.ShowAsync()" />
<MBDialog @ref="dialog">
    <MBNumericDoubleField @bind-Value="value" />
</MBDialog>
```

and the error I get is

```log
FocusTrap: Element must have at least one focusable child.
    at FocusTrap.trapFocus (MaterialBlazor.js:17083)
    at Object.trapFocus (MaterialBlazor.js:17733)
    at MaterialBlazor.js:17344
```

So there is an issue we need to figure out, but let's find out why you get a different error first.

BR
Stefan

**Comment by stefanloerwald** [comment] 2021-04-22 13:06
Hi @martindekock,

here's a status update: I've identified the issue (and also found out why my code didn't work: I forgot to put that field into the `Body`...) and submitted a PR that fixes it. There are still some issues around focus & dialogs that I want to find the root cause of, but at least it'll not throw errors when #482 is merged.

BR
Stefan

**Closed as completed** 2021-04-26 20:53 UTC
