### ISSUE TITLE
MBSelect Bug

### ISSUE THREAD

**Issue by Johan-allegiance** [Material-Blazor/Material.Blazor#475] opened 2021-04-16 08:54 UTC
Hi, 
So when I use tab to tab to my MBSelect element, I then use my keyboard arrow keys to navigate to the selection I want, and then I use tab again to tab to the next field. At that moment it doesn't register any change. It displays the new selected value, but doesn't register any changes so my property did not change. Only if instead of tab I press enter, then it registers the change. Can you possibly fix that? I really enjoy your components and wish to keep using it.

**Comment by stefanloerwald** [comment] 2021-04-16 11:56
Hi @Johan-allegiance,

this looks very much like it's the design material intends to follow. See for example https://material-components.github.io/material-components-web-catalog/#/component/select, which is the demo for the reference implementation. For keyboard selection, pressing enter is required for the selection to be made. Using tab is essentially the same as escape: it aborts the change action. So this is by design and not a bug.

BR
Stefan

**Comment by simonziegler** [comment] 2021-04-16 13:12
@Johan-allegiance we are using Material Theme as Google have implemented it, and this is their design. When using the keyboard you need to press enter once you have found your selected value.

One note - we have recently fixed a bug here (#463), whereby this actually didn't work! This will be released in version 2 preview 4 soon.

**Closed as completed by simonziegler** 2021-04-16 13:12 UTC
